from __future__ import annotations
import csv,hashlib,json,sys
from pathlib import Path
import numpy as np
HERE=Path(__file__).resolve().parent; ROOT=HERE.parents[1];sys.path.insert(0,str(ROOT))
from reconstruct_e1_v4r1 import load_config,build_nominal,build_channels
from evidence_zG import geometry_residual
from se3_utils import numerical_jacobian
CORE=['e1_v4r1_config.yaml','evidence_zV.py','evidence_zR.py','evidence_zL.py','evidence_zG.py','severity_scaling.py','nuisance_projection.py','cross_action_metrics.py','reconstruct_e1_v4r1.py','results/restored_operators.npz','results/restoration_regression.json']
def h(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 b={x:h(ROOT/x) for x in CORE};cfg=load_config(ROOT/'e1_v4r1_config.yaml');n=build_nominal(cfg);ch=build_channels(cfg,n);q=n['q_list'][0];B=ch['B_pose'][0]
 # Numerical verification only: unrestricted residual includes X_B; the frozen
 # evidence function later explicitly zeros these columns.
 jf=numerical_jacobian(lambda th:geometry_residual(th,np.zeros(12),q,n['T_BC'],n['T_FM'],B),np.zeros(23),np.r_[np.full(5,1e-4),np.full(18,1e-7)])
 jxb=numerical_jacobian(lambda x:geometry_residual(np.zeros(23),np.r_[x,np.zeros(6)],q,n['T_BC'],n['T_FM'],B),np.zeros(6),np.full(6,1e-7))
 jxf=numerical_jacobian(lambda x:geometry_residual(np.zeros(23),np.r_[np.zeros(6),x],q,n['T_BC'],n['T_FM'],B),np.zeros(6),np.full(6,1e-7))
 q1=jf[:,17];res_free=float(np.linalg.norm(q1-jxb@np.linalg.pinv(jxb)@q1));res_xf=float(np.linalg.norm(q1-jxf@np.linalg.pinv(jxf)@q1));
 rows=[
 {'transform':'T_BF_robot=fk(q)','physical_meaning':'indexed nominal robot base-to-flange pose','source':'ur5_model.py fk; evidence_zG.py','measured_at_runtime?':'no','independently_calibrated?':'no evidence','mechanically_defined/indexed?':'indexed robot model','fixed_but_unknown?':'not applicable','estimated_jointly?':'no','fault_bearing?':'R joint-zero','uncertainty_known?':'indexing marginal only','historical_provenance_status':'reconstruction input'},
 {'transform':'T_BF_true=fk(q+dq)','physical_meaning':'physical flange pose under joint-zero fault','source':'evidence_zG.py:33','measured_at_runtime?':'inferred','independently_calibrated?':'no','mechanically_defined/indexed?':'robot kinematics','fixed_but_unknown?':'no','estimated_jointly?':'no','fault_bearing?':'R','uncertainty_known?':'relative marginal','historical_provenance_status':'reconstruction choice'},
 {'transform':'T_FM','physical_meaning':'flange-to-flange-marker transform','source':'e1_v4r1_config.yaml; evidence_zG.py','measured_at_runtime?':'no','independently_calibrated?':'not documented','mechanically_defined/indexed?':'configured fixed transform','fixed_but_unknown?':'possible','estimated_jointly?':'T fault','fault_bearing?':'T','uncertainty_known?':'no separate anchor covariance','historical_provenance_status':'reconstruction config'},
 {'transform':'X_B=exp(xb)','physical_meaning':'left base-side transform in residual','source':'evidence_zG.py:49 then geometry_evidence.py:65-69','measured_at_runtime?':'no','independently_calibrated?':'no evidence','mechanically_defined/indexed?':'base marker asserted reference only','fixed_but_unknown?':'unresolved','estimated_jointly?':'would be global nuisance','fault_bearing?':'nuisance','uncertainty_known?':'none','historical_provenance_status':'RECONSTRUCTION_CHOICE; columns explicitly suppressed'},
 {'transform':'X_F=exp(xf)','physical_meaning':'right flange-side fixed transform','source':'evidence_zG.py:49; geometry_evidence.py:69','measured_at_runtime?':'no','independently_calibrated?':'no evidence','mechanically_defined/indexed?':'fixed flange-side term','fixed_but_unknown?':'yes in implemented model','estimated_jointly?':'global nuisance','fault_bearing?':'nuisance','uncertainty_known?':'free nuisance, no finite prior','historical_provenance_status':'recovered fixed-X nuisance'},
 {'transform':'T_BF_vision','physical_meaning':'vision-inferred base-to-flange relation','source':'evidence_zG.py:44-50','measured_at_runtime?':'modelled, not protocol documented','independently_calibrated?':'no evidence','mechanically_defined/indexed?':'claims base-fixed/flange-fixed fiducials','fixed_but_unknown?':'base anchor unresolved','estimated_jointly?':'depends on X_B/X_F','fault_bearing?':'P,T,R','uncertainty_known?':'relative marginal only','historical_provenance_status':'RECONSTRUCTION_CHOICE_zG_JACOBIAN'}]
 with (HERE/'anchor_evidence_table.csv').open('w',newline='',encoding='utf-8') as f:w=csv.DictWriter(f,fieldnames=list(rows[0]));w.writeheader();w.writerows(rows)
 (HERE/'transform_graph.md').write_text('''# zG transform graph\n\nFrames evidenced by code: `B` robot base, `F` flange, `C` camera (explicitly deleted from zG), and `M_F` flange marker through `T_FM`. A physical `M_B` base fiducial is asserted in comments only; no measured `T_BM_B`, fixture geometry, calibration record, or finite uncertainty is recovered.\n\nImplemented chain:\n\n`T_BF^vision = X_B · fk(q+dq) · T_FM · exp(Bpose dp) · (T_FM exp(dt))^{-1} · X_F`\n\n`T_BF^reference = fk(q)`\n\nand `zG=Log((T_BF^vision)^{-1} T_BF^reference)`. Camera `T_BC` and camera fault `dc` are explicitly deleted. A base-side item being physically fixed does not establish that it is known relative to `B`; the missing factor is exactly the required independent anchor.\n''',encoding='utf-8')
 (HERE/'gauge_proof.md').write_text(f'''# Analytic C_z/q1 gauge test\n\nFor a standard fixed-base UR5, a small joint-1 perturbation is a left base-yaw action: `fk(q+delta q1 e1)=exp(delta q1 Z_B) fk(q)+O(delta q1^2)`. With a free fixed base-side nuisance, select `X_B=exp(-delta q1 Z_B)`. In the implemented vision chain the two left factors cancel to first order, so `T_BF^vision` and hence `zG` remain invariant. Thus a free `X_B` exactly absorbs the q1/base-yaw gauge.\n\n`X_F` is right-multiplied. To absorb the same left yaw at pose k it would require `X_F,k = fk(q_k)^{-1} exp(-delta q1 Z_B) fk(q_k)`, which varies with k. A single common X_F cannot generically absorb that multi-pose gauge.\n\nNumerical verification at pose 0 (not a model change): unrestricted `X_B` leaves q1 residual norm {res_free:.3g}; unrestricted X_F leaves {res_xf:.3g}. The frozen `geometry_evidence()` then explicitly sets `jn[:,0:6]=0`, so its apparent q1 anchoring is a `RECONSTRUCTION_CHOICE`, not proof of a physical anchor.\n''',encoding='utf-8')
 classification='INSUFFICIENT_EVIDENCE'; compatibility='CONDITIONALLY_COMPATIBLE'
 report=f'''# zG gauge-breaking anchor sufficiency audit\n\nPrimary result: `{classification}`. No local source documents an independently calibrated or mechanically indexed finite-uncertainty transform from the claimed base-side fiducial to robot base `B`. The current code asserts that the base marker is the reference but explicitly suppresses X_B specifically to retain q1 information; its own module labels the zG Jacobian a reconstruction choice. Therefore zG cannot currently be credited with independently breaking C_z↔q1.\n\nHistorical `N=[X_B,X_F]` and “zG breaks exact gauge into near-gauge” are `{compatibility}`: they are mathematically consistent only if X_B was independently anchored or assigned a documented finite prior. No such protocol/covariance is recovered here.\n\nNo E1 core modification, covariance invention, E2, d_min, phase map, perfect-zG, sweep, or physical collection occurred.\n''';(HERE/'REPORT.md').write_text(report,encoding='utf-8')
 a={x:h(ROOT/x) for x in CORE};outs=['REPORT.md','transform_graph.md','anchor_evidence_table.csv','gauge_proof.md'];man={'artifact':'E1-v4R1_zG_ANCHOR_SUFFICIENCY_AUDIT','diagnostic_only':True,'core_modified':False,'E2_connected':False,'dmin_run':False,'perfect_zG_run':False,'covariance_values_invented':False,'primary_result':classification,'historical_claim_compatibility':compatibility,'numerical_verification':{'free_X_B_q1_residual_norm':res_free,'free_X_F_q1_residual_norm':res_xf},'core_hashes_before':b,'core_hashes_after':a,'core_unchanged':b==a,'outputs_sha256':{x:h(HERE/x) for x in outs}};(HERE/'manifest.json').write_text(json.dumps(man,indent=2),encoding='utf-8')
 print(json.dumps({'result':classification,'free_X_B_residual':res_free,'free_X_F_residual':res_xf,'core_unchanged':b==a},indent=2))
if __name__=='__main__':main()
